## Books {#books .unnumbered}

::: bibitem
Scrucca L., Fraley C., Murphy T. B. and Raftery A. E. (2023)
**Model-Based Clustering, Classification, and Density Estimation Using
mclust in R**, Chapman & Hall/CRC, ISBN: 978-1032234953.
<https://doi.org/10.1201/9781003277965>
:::

## Journal articles {#journal-articles .unnumbered}

::: bibitem
Scrucca L., (2024) Assessing uncertainty in Gaussian mixtures-based
entropy estimation. **Under review**.\
arXiv pre-print available at <https://arxiv.org/abs/2405.17265>

Scrucca L., Karlis D. (2024) A model-based approach to shot charts
estimation in basketball. **Under review**.\
arXiv pre-print available at <https://arxiv.org/abs/2405.01182>

Tiburtini M., Scrucca L. and Peruzzi L. (2024) A guide to plant
morphometrics using Gaussian Mixture Models. **Under review**.\
bioRxiv pre-print available at
<https://doi.org/10.1101/2024.04.21.590472>

Scrucca L. (2023) On the influence of data imbalance on supervised
Gaussian mixture models. **Algorithms**, 16(12), 563.
<https://doi.org/10.3390/a16120563>

Scrucca L. (2023) Entropy-based anomaly detection for Gaussian mixture
modeling. **Algorithms**, 16(4), 195.
<https://doi.org/10.3390/a16040195>

Robin S., Scrucca L. (2023) Mixture-based estimation of entropy.
**Computational Statistics & Data Analysis**, 177, 107582.
<https://doi.org/10.1016/j.csda.2022.107582>

Santini F., Elisei L., Malmi T. and Scrucca L. (2022)
Management-control-system configurations in medium-sized
mechanical-engineering firms: an exploratory analysis, **Accounting
Research Journal**, 35(6), 834--853.
<https://doi.org/10.1108/ARJ-06-2021-0168>

Scrucca L. (2022) Modal clustering on PPGMMGA projection subspace.
**Australian & New Zealand Journal of Statistics**, 64:2, 158--170.
<https://doi.org/10.1111/anzs.12360>

Scrucca L. (2022) A COVINDEX based on a GAM beta regression model with
an application to the COVID-19 pandemic in Italy. **Statistical Methods
& Applications**, 31:4, 881--900.
<https://doi.org/10.1007/s10260-021-00617-y>

Chirieleison C., Montrone A., Scrucca L. (2022) Destination labels for
historic villages: the impact on perception, experience, and
satisfaction. **Tourism and Hospitality Research**, 22:2, 164--179.
<https://doi.org/10.1177/14673584211020788>

Scrucca L. (2021) A fast and efficient Modal EM algorithm for Gaussian
mixtures. **Statistical Analysis and Data Mining**, 14:4, 305--314.
<https://doi.org/10.1002/sam.11527>

Casa A., Scrucca L., Menardi G. (2021) Better than the best? Answers via
model ensemble in density-based clustering. **Advances in Data Analysis
and Classification**, 15, 599---623.
<https://doi.org/10.1007/s11634-020-00423-6>

Chirieleison C., Montrone A., Scrucca L. (2020) Event sustainability and
sustainable transportation: a positive reciprocal influence. **Journal
of Sustainable Tourism**, 28:2, 240--262.
<https://doi.org/10.1080/09669582.2019.1607361>

Scrucca L., Serafini A. (2019) Projection pursuit based on Gaussian
mixtures and evolutionary algorithms. **Journal of Computational and
Graphical Statistics**, 28:4, 847--860.
<https://doi.org/10.1080/10618600.2019.1598871>

O'Hagan A., Murphy T. B., Scrucca L. and Gormley I. C. (2019)
Investigation of parameter uncertainty in clustering using a Gaussian
mixture model via jackknife, bootstrap and weighted likelihood
bootstrap. **Computational Statistics**, 34, 1779---1813.
<https://doi.org/10.1007/s00180-019-00897-9>

Fop M., Murphy T. B., Scrucca L. (2019) Model-based clustering with
sparse covariance matrices. **Statistics and Computing**, 29:4,
791--819. <https://doi.org/10.1007/s11222-018-9838-y>

Scrucca L. (2019) A transformation-based approach to Gaussian mixture
density estimation for bounded data. **Biometrical Journal**, 61:4,
873--888. <https://doi.org/10.1002/bimj.201800174>

Ndabashinze B., Ustundag Siray G., Scrucca L. (2019) Genetic algorithms
applied to fractional polynomials for power selection: application to
diabetes data, **Turkish Journal of Forecasting**, 3, 15--25.
<https://doi.org/10.34110/forecasting.514761>

Giustozzi M., Vedovati M. C., Verso M., Scrucca L., Conti S., Verdecchia
P., Bogliari G., Pierpaoli L., Agnelli G. and Becattini C. (2019)
Patients aged 90 years or older with atrial fibrillation treated with
oral anticoagulants: A multicentre observational study. **International
Journal of Cardiology**, 281, 56--61.
<https://doi.org/10.1016/j.ijcard.2019.01.071>

Giustozzi M., Vedovati M. C., Verso M., Scrucca L., Conti S., Verdecchia
P., Bogliari G., Pierpaoli L., Agnelli G. and Becattini C. (2019) Data
on the use of oral anticoagulants in nonagenarians with atrial
fibrillation, **Data in Brief**, Vol. 23, 103794.
<https://doi.org/10.1016/j.dib.2019.103794>

Chirieleison C., Montrone A., Scrucca L. (2018) Eventi e mobilità
sostenibile: un modello basato sulla cluster analysis. **Economia della
Cultura**, anno XXVIII, 2018, n. 4.

Scrucca L. and Raftery A. E. (2018) clustvarsel: A Package Implementing
Variable Selection for Gaussian Model-based Clustering in R. **Journal
of Statistical Software**, 84:1, 1--28.
<http://doi.org/10.18637/jss.v084.i01>

Chirieleison C., Montrone A., Scrucca L. (2017) La mobilità sostenibile
durante i grandi eventi italiani: un'analisi con il model-based
clustering approach. **Turistica**, anno XXVI, vol. 4, 35--55.

Chirieleison C. and Scrucca L. (2017) Event sustainability and
transportation policy: a model-based cluster analysis for a
cross-comparison of hallmark events. **Tourism Management
Perspectives**, 24, 72--85. <https://doi.org/10.1016/j.tmp.2017.07.020>

Chirieleison C. and Scrucca L. (2017) Shaping students' attitudes
towards business ethics and corporate social responsibility: education
versus personal perspectives, **Education**, 7:5, 83--95.
<http://article.sapub.org/10.5923.j.edu.20170705.01.html>

Scrucca L. (2017) On some extensions to GA package: hybrid optimisation,
parallelisation and islands evolution, **The R Journal**, 9:1, 187--206.
<https://doi.org/10.32614/RJ-2017-008>

Parisi A., Scrucca L., Desiderio J., Gemini A., Guarino S., Ricci F.,
Cirocchi R., Palazzini G., D'Andrea V., Minelli L., Trastulli S. (2017)
Robotic right hemicolectomy: Analysis of 108 consecutive procedures and
multidimensional assessment of the learning curve, **Surgical
Oncology**, 26:1, 28--36. <http://doi.org/10.1016/j.suronc.2016.12.005>

Scrucca L., Fop M., Murphy T. B. and Raftery A. E. (2016) mclust 5:
clustering, classification and density estimation using Gaussian finite
mixture models, **The R Journal**, 8:1, 205--233.
<https://doi.org/10.32614/RJ-2016-021>

Scrucca L. (2016) Identifying connected components in Gaussian finite
mixture models for clustering. **Computational Statistics & Data
Analysis**. 93, 5--17. <http://dx.doi.org/10.1016/j.csda.2015.01.006>

Sahdra B., Ciarrochi J., Parker P. and Scrucca L. (2016) Using genetic
algorithms in a large nationally representative American sample to
abbreviate the Multidimensional Experiential Avoidance Questionnaire.
**Frontiers in Psychology**, 7:189, 1--14.
<https://doi.org/10.3389/fpsyg.2016.00189>

Scrucca L. and Raftery A. E. (2015) Improved initialisation of
model-based clustering using Gaussian hierarchical partitions.
**Advances in Data Analysis and Classification**, 9:4, 447--460.
<https://doi.org/10.1007/s11634-015-0220-z>

Cencetti C., de Rosa P., Fredduzzi A., Minelli A., and Scrucca L. (2015)
A statistical test for drainage network recognition using MeanStreamDrop
analysis. **Geomatics, Natural Hazards and Risk**, 5--7, 534--553.
<https://doi.org/10.1080/19475705.2014.897655>

Scrucca L. (2014) Graphical tools for model-based mixture discriminant
analysis. **Advances in Data Analysis and Classification**, 8:2,
147--165. <https://doi.org/10.1007/s11634-013-0147-1>

Morris K., McNicholas P., and Scrucca L. (2013) Dimension reduction for
model-based clustering via mixtures of multivariate t-distributions.
**Advances in Data Analysis and Classification**, 7:3, 321--338.
<https://doi.org/10.1007/s11634-013-0137-3>

Scrucca L. (2013) GA: A Package for Genetic Algorithms in R. **Journal
of Statistical Software**, 5:4, 1--37.
<http://www.jstatsoft.org/v53/i04>

Chirieleison C., Montrone A., Scrucca L. (2013) Measuring the impact of
a profit oriented event on tourism: the Eurochocolate festival in
Perugia, Italy. **Tourism Economics**, 19:6, 1411--1428.
<https://doi.org/10.5367%2Fte.2013.0269>

Chirieleison C., Montrone A., Scrucca L. (2012) L'impatto degli eventi
sul territorio: il caso Eurochocolate. **AUR&S**, 7-8:12, 133--156.

Scrucca L. (2011) Model-based SIR for dimension reduction.
**Computational Statistics & Data Analysis**, 55:11, 3010--3026.
<https://doi.org/10.1016/j.csda.2011.05.006>

Scrucca L. (2010) Dimension Reduction for Model-Based Clustering.
**Statistics and Computing**, 20:4, 471--484.
<https://doi.org/10.1007/s11222-009-9138-7>

Scrucca L., Santucci A., Aversa F. (2010) Regression Modeling of
Competing Risk Using R: An In Depth Guide for Clinicians. **Bone Marrow
Transplantation**, 45, 1388--1395.
<https://doi.org/10.1038/bmt.2009.359>

Scrucca L. (2007) Class prediction and gene selection for DNA
microarrays using sliced inverse regression. **Computational Statistics
& Data Analysis**, 52, 438--451.
<https://doi.org/10.1016/j.csda.2007.02.005>

Scrucca L., Santucci A., Aversa F. (2007) Competing risks analysis using
R: an easy guide for clinicians. **Bone Marrow Transplantation** (2007)
40, 381--387. <https://doi.org/10.1038/sj.bmt.1705727>

Scrucca L. (2004) L'identificazione dei distretti industriali e delle
aree di sviluppo economico omogenee e/o integrate. **Rivista
dell'Agenzia Umbria Ricerche**, 1, 71--90.

Scrucca L. (2004) qcc: an R package for quality control charting and
statistical process control. **R News**, 4:1, June 2004, 11-17.
<https://cran.r-project.org/doc/Rnews/Rnews_2004-1.pdf>

Scrucca L., Weisberg S. (2004) A simulation study to investigate the
behavior of the log-density ratio under normality. **Communications in
Statistics (simulation and computation)**, 33:1, 159--178.
<https://doi.org/10.1081/SAC-120028439>

De Angelis M., Scrucca L., Leandri M., Mincigrucci S., Bistoni S., Bovi
M., Calabrese G., Pippi R., Parretti D., Grilli P., Colorio P.,
Fattorini M., Flamini O., Pacetti E., Travaglini A., Santeusanio F.
(2003) Prevalence of carotid stenosis in type 2 diabetic patients
asymptomatic for cerebrovascular disease. **Diabetes, Nutrition &
Metabolism**, 16:1, 48--55.

Scrucca L. (2002) Graphics for studying logistic regression models.
**Statistical Methods & Applications**, 11:3, 371--394.
<https://doi.org/10.1007/BF02509833>

Scrucca L. (2001) Nonparametric kernel smoothing methods. The sm library
for Xlisp-Stat. **Journal of Statistical Software**, 6.
<http://www.jstatsoft.org/v06/i07>

Scrucca L. (2001) A review and computer code for assessing the
structural dimension of a regression model: uncorrelated 2D views.
**Computational Statistics & Data Analysis**, 36:2, 163--177.
<https://doi.org/10.1016/S0167-9473(00)00035-9>

Scrucca L. (2000) Assessing multivariate normality through interactive
dynamic graphics. **Quaderni di Statistica**, 2, 221--240.

Scrucca (1996) I sondaggi elettorali nella recente esperienza italiana.
**Induzioni**, n. 12, 59--81.
:::

## Book chapters {#book-chapters .unnumbered}

::: bibitem
Scrucca L., Saqr M., López-Pernas S., Murphy K. (2024) An introduction
and R tutorial to model-based clustering in education via latent profile
analysis. In: Saqr M. & López-Pernas S. (Eds.), **Learning analytics
methods and tutorials: A practical guide using R**. Springer.
<https://lamethods.org/chapters/ch09-model-based-clustering/ch9-model.html>

Serafini A., Scrucca L., Alfò M., Giordani P., Ferraro M. B. (2023)
Fuzzy and model based clustering methods: can we fruitfully compare
them? In: Brentari, E., Chiodi, M., Wit, EJ.C. (eds) **Models for Data
Analysis**. SIS 2018, 49th Meeting of Italian Statistical Society,
Palermo, Italy, June 20--22. Springer Proceedings in Mathematics &
Statistics, pp. 283--304.

Scrucca L. (2016) Genetic algorithms for subset selection in model-based
clustering. In **Unsupervised Learning Algorithms**, Celebi M. E. and
Aydin K. (editors), Springer International Publishing, pp. 55--70.

Chirieleison C., Scrucca L. (2016) CSR education in Italy. In **Social
Responsibility Education Across Europe. A Comparative Approach**, Turker
D., Altuntas Vural C., Idowu S. O. (editors), Springer International
Publishing, pp. 139--159.

Scrucca L., Bar-Hen A. (2013) A model-based dimension reduction approach
to classification of gene expression data. In **Advances in Theoretical
and Applied Statistics**, Torelli N., Pesarin F., Bar-Hen A. (editors),
Springer, pp. 221--230.

Scrucca L. (2011) A Geometric Approach to Subset Selection and Sparse
Sufficient Dimension Reduction. In **New Perspectives in Statistical
Modeling and Data Analysis**, editors Ingrassia S., Rocci R., Vichi M.,
Springer-Verlag, Berlin Heidelberg, pp. 569--576.

Bartolucci F., Scrucca L. (2010) Point Estimation Methods with
Applications to Item Response Theory Models. In **International
Encyclopedia of Education**, Penelope Peterson, Eva Baker, Barry McGaw
(editors), 3rd edition, Oxford: Elsevier, Vol. 7, pp. 366--373.

Scrucca L. (2010) Visualization of model-based clustering structures. In
**Data Analysis and Classification**, editors Palumbo F., Lauro C.,
Greenacre M., Berlin, Springer-Verlag, pp. 67--75.

Scrucca L. (2006) Regularized sliced inverse regression with
applications in classification. In **Data Analysis, Classification and
the Forward Search**, editors Zani S., Cerioli A., Riani M., Vichi M.,
Berlin, Springer-Verlag, pp. 59--66.

Scrucca L. (2005) La metodologia utilizzata per l'identificazione di
aggregazioni sub-regionali omogenee. In *Verso una rilettura dei sistemi
locali dell'Umbria: prime applicazioni di una nuova metodologia di
clusterizzazione*, **Quaderni PRASSI - Agenzia Umbria Ricerche**, Cap.
2.

Scrucca L. (2003) Aree di sviluppo omogenee e/o integrate. Approcci e
metodologie. **Paper dell'Agenzia Umbria Ricerche**, Collana: sviluppo e
locale, n. 8, pp. 1--47.
:::

## Conferences and workshops {#conferences-and-workshops .unnumbered}

::: bibitem
Scrucca L. (2024) A Model-Based Approach to Shot Charts Estimation in
Basketball, **Working Group on Model-Based Clustering**. Bertinoro, July
22--26, 2024.

Scrucca, L. (2023) Gaussian Mixture Models for Probabilistic Learning,
**From Physics to Medicine: eXplainable AI workshop**, Milano, November
20--22, 2023.

Scrucca, L. (2023) Anomaly Detection of Financial Ratios using Gaussian
Mixture Models, **Workshop Annuale del Dipartimento di Economia 2023
(WADE 2023)**, Department of Economics, 30--31 October 2023 (Session II
31-10, Part 2.1.8), Zenodo. https://doi.org/10.5281/zenodo.10053896

Scrucca L. (2023) Mixture-based Estimation of Entropy and Its
Applications, **Working Group on Model-Based Clustering**. Carnegie
Mellon University, Pittsburgh (US), July 17--21, 2023.

Scrucca L. (2022) Gaussian mixtures using range-logit transformation
with an application to image segmentation. **MBC2 Book of Abstracts**,
6th International Workshop on Models and Learning for Clustering and
Classification, Catania, 31 August -- 2 September 2022, pp. 11--12.

Scrucca L. (2022) Silhouette Analysis for Model-Based Clustering, **ECDA
2022, European Conference on Data Analysis**, Naples, Italy, September
14--16 2022.

Scrucca L. (2021) Stacking ensemble of Gaussian mixtures for
classification, **Working Group on Model-Based Clustering**. Athens
University of Economics and Business, Athens, October 25--30, 2021.

Scrucca L. (2021) Stacking ensemble learning with Gaussian mixtures. In
**CLADAG 2021 Book of Abstracts and Short Papers. 13th Scientific
Meeting of the Classification and Data Analysis Group** (editors
Giovanni C. Porzio, Carla Rampichini, Chiara Bocci), Firenze University
Press, pp. 420--423. Firenze, September 9--11 2021.

Scrucca L. (2021) Statistical models for infectious diseases
epidemiology, **COST Action: CA18208 - Novel tools for test evaluation
and disease prevalence estimation**, Training School, Perugia, September
16--17 2021.

Scrucca L., Serafini A. (2019) Mutual information Estimation via
Gaussian Mixture Modelling, **Working Group on Model-Based Clustering**.
WU Vienna University of Economics and Business, Vienna, July 14--20,
2019.

Scrucca L. (2019) A fast and efficient Modal EM algorithm for Gaussian
mixtures. In **CLADAG 2019 Book of Short Papers. 12th Scientific Meeting
of the Classification and Data Analysis Group** (editors Giovanni C.
Porzio, Francesca Greselin, Simona Balzano), Edizioni Università di
Cassino, pp. 432--435. Cassino, September 11--13 2019.

Casa A., Scrucca L., Menardi G. (2018) Averaging via Stacking in
Model-based Clustering, **MBC2 -- Workshop on Model Based Clustering and
Classification**. Catania, 5--7 September, 2018.

Alfò M., Ferraro M.B, Giordani P., Scrucca L., Serafini A. (2018)
Model-based clustering vs Fuzzy clustering: a simulation comparison,
**Working Group on Model-Based Clustering**. University of Michigan, Ann
Arbor (USA), July 15--21, 2018.

Alfò M., Ferraro M.B, Giordani P., Scrucca L., Serafini A. (2018) A
Comparison of Model-Based and Fuzzy Clustering Methods. **SIS2018, 49th
Scientific Meeting of the Italian Statistical Society**. Palermo, 20--22
June, 2018. Abbruzzo A., Brentari E., Chiodi M., Piacentino D.
(editors), Book of Short Papers SIS 2018, Pearson, pp. 208--215.

Casa A., Scrucca L., Menardi G. (2018) On the Selection Uncertainty in
Parametric Clustering, **ECDA 2018, European Conference on Data
Analysis**, Paderborn, Germany, July 04--06 2018, Book of Abstracts, pp.
22--23.

Piersanti A., Tavoloni T., Scrucca L., Galarini R. (2018) Validation
Data Processing by ADVeRSE 2.0 Free Software Package: Assessment of the
Analytical Requirements of a GC-MS Method for the Determination of 16
PAHs in Smoked Fish, **XXII International Mass Spectrometry Conference
(IMSC)**, 26--31 August 2018, Florence.

Fop M., Murphy T.B., Scrucca L. (2017) Model-based Clustering with
Sparse Covariance Matrices. **SIS 2017. Statistics and Data Science: new
challenges, new generations**. Florence, 28--30 June, 2017. Petrucci A.,
Verde R. (editors), Proceedings of the Conference of the Italian
Statistical Society, pp. 437--440.

Scrucca L., Fop M., Murphy T.B., Raftery A.E. (2017) The mclust R
package for clustering, classification and density estimation using
Gaussian finite mixture models, **10th International Conference of the
ERCIM WG on Computational and Methodological Statistics, 11th
International Conference on Computational and Financial Econometrics**,
Senate House, University of London, UK, December 16-18 2017, Book of
Abstracts, p. 175.

Scrucca L. (2017) Boosting Gaussian mixture models for classification,
**Working Group on Model-Based Clustering**. Università degli Studi di
Perugia, Perugia, July 17---21, 2017.

Scrucca L. (2016) On some recent improvements to mixture modelling
estimation: Gaussian hierarchical partitions based on data
transformations and evolutionary EM, **Working Group on Model-Based
Clustering**. Université Paris Descartes, Paris, July 17--23, 2016.

Scrucca L. (2016) Poisson change-point models estimated by genetic
algorithms. In **SIS2016, 48th Scientific Meeting of the Italian
Statistical Society**. Salerno, 8--10 June, 2016.

Scrucca L. (2015) A quick tour of new functionalities in MCLUST version
5, **Working Group on Model-Based Clustering**. University of
Washington, Seattle, July 19--25, 2015.

Galarini R., Moretti S., Romanelli S., Scrucca L. (2015) Informatics
tools to manage validation data of multiresidue analytical methods.
MASSA 2015, Alghero (Italy), June 2015.

Scrucca L. (2014) Identifying connected components in Gaussian finite
mixture models for clustering, **Workshop on "Clustering methods and
their applications"**. Free University of Bozen - Bolzano, November
28th, 2014.

Scrucca L. (2014) Model-based density estimation for bounded data,
**Working Group on Model-Based Clustering**. University College Dublin,
Dublin, July 20--26, 2014.

Scrucca L., Raftery A. E. (2014) Improved initialisation of model-based
clustering using a Gaussian hierarchical partition, **MBC2 -- Workshop
on Model Based Clustering and Classification**. Catania, 3--5 September,
2014.

Scrucca L. (2013) Identifying connected components in model-based
clustering, **Working Group on Model-Based Clustering**. Università di
Bologna, July 21--27, 2013.

Scrucca L. (2013) On the implementation of a parallel algorithm for
variable selection in model-based clustering. **CLADAG 2013. 9th
Scientific Meeting of the Classification and Data Analysis Group. Book
of Abstracts** (editors Tommaso Minerva, Isabella Morlini, Francesco
Palumbo). Cleup. 9th Meeting of the CLassification and Data Analysis
Group of the Italian Statistical Society, Modena, 18--20 September 2013.

Scrucca L. (2012) MCLUST version 4 session, **Working Group on
Model-Based Clustering**. University of Guelph, July 16--20, 2012.

Scrucca L. (2012) Graphical tools for model-based mixture discriminant
analysis, **MBC2 -- Workshop on Model Based Clustering and
Classification**, Catania, 6--7 September 2012

Scrucca L. (2011) Genetic algorithms for subset selection in model-based
clustering, **Working Group on Model-Based Clustering**, University of
Glasgow, Glasgow, July 17--23, 2011.

Scrucca L. (2011) Classification on a dimension reduced subspace.
**CLADAG 2011, Book of Abstracts** (editors Paola Cerchiello, Claudia
Tarantola), Pavia University Press, p. 47. 8th Scientific Meeting of the
CLAssification and Data Analysis Group of the Italian Statistical
Society, Pavia, 7--9 September 2011.

Scrucca L. (2010) Some recent advances on dimension reduction for
high-dimensional data. In **GfKL-CLADAG 2010, Book of Abstracts**, pp.
99--100. Joint meeting GfKl-CLADAG 2010, 8--10 September 2010.

Scrucca L., Bar-Hen A. (2010) A model-based dimension reduction approach
to classification of gene expression data. In **SIS2010, Atti della XLV
Riunione Scientifica della Società Italiana di Statistica**, CLEUP.
Padova, 16--18 June, 2010.

Scrucca L. (2010) Genetic algorithms for subset selection in model-based
clustering. In **SIS2010, Atti della XLV Riunione Scientifica della
Società Italiana di Statistica** CLEUP. Padova, 16-18 June, 2010.

G. Saluti, Galarini R., Scrucca L. (2010) Multivariate Charts for
Quality Control of Multiresidue Analytical Methods. In *Sixth
International Symposium on Hormone and Veterinary Drug Residue
Analysis*, Ghent (Belgium) 1-4 June 2010.

Scrucca L. (2009) A Finite Mixture Model Approach to Sliced Inverse
Regression, **Working Group on Model-Based Clustering**. Institut Henri
Poincaré, Paris, July 19--25, 2009.

Scrucca L. (2009) A Geometric Approach to Subset Selection and Sparse
Sufficient Dimension Reduction. In **CLADAG 2009, Book of Short Papers**
(editors Ingrassia S. e Rocci R.), Padova, CLEUP, pp. 235--238. VII
Riunione Scientifica del Gruppo di Classificazione e Analisi dei Dati
della Società Italiana di Statistica, Catania, 9--11 September 2009.

Scrucca L. (2008) A mixture model approach to dimension reduction in
regression (Un approccio basato sui modelli mistura per la riduzione
della dimensionalità nell'ambito della regressione). In **SIS2008, Atti
della XLIV Riunione Scientifica della Società Italiana di Statistica**,
pp. 233--240. Arcavacata di Rende, 25--27 June, 2008.

Scrucca L. (2007) Dimension reduction and visualization for model-based
clustering, **Working Group on Model-Based Clustering**. Trinity College
Dublin, Dublin, July 16--20, 2007.

Scrucca L. (2007) Visualization of model-based clustering structures. In
**CLADAG 2007, Book of Short papers**, Lauro C. e Palumbo F. (editors),
pp. 451--454. VI Riunione Scientifica del Gruppo di Classificazione e
Analisi dei Dati della Società Italiana di Statistica, Macerata 12-14
September 2007.

Scrucca L. (2006) Dimension reduction and visualization for model-based
clustering. In **COMPSTAT 2006, Book of abstracts**, 17th Symposium of
IASC on Computational Statistics, Rome, 28 Agust - 1 September 2006.

Piersanti A., Galarini R., Tavoloni T., Scrucca L. (2006)
Polychlorobiphenyl (18 congeners) in mussels from middle adriatic sea.
In **Proceedings of 26th International Symposium on Halogenated
Persistent Organic Pollutants - DIOXIN 2006**, Oslo, 21-25 August 2006,
pp. 1951--1954. Organohalogen Compounds Vol. 68.

Scrucca L. (2005) Regularized sliced inverse regression with
applications in classification. In **CLADAG 2005, Book of Short papers**
(editors Zani S. e Cerioli A.), pp. 509--512. V Riunione Scientifica del
Gruppo di Classificazione e Analisi dei Dati della Società Italiana di
Statistica, Parma 6-8 giugno 2005.

Scrucca L. (2004) Class prediction and gene selection for DNA
microarrays using sliced inverse regression. In **Proceedings of the
19th International Workshop on Statistical Modelling (IWSM 2004)**,
Firenze, 4-8 July 2004, pp. 259--263.

Scrucca L. (2003) On a test procedure for assessing a parametric
approximation to a nonlinear term in semiparametric models. In
**Proceedings ISI 2003 - International Statistical Institute** (13-20
August 2003, Berlin, Germany), Contributed Papers, Vol. LX, Book 2, pp.
397--398.

Scrucca L. (2002) Robust sliced inverse regression and outliers
detection. In **Euroworkshop on Statistical Modelling Model Building and
Evaluation**, Bernried, Germany, Oct 31-Nov 3 2002.

Porzio G.C., Scrucca L. (2002) Visualizing the correlation coefficient
(Il coefficiente di correlazione: una sua rappresentazione grafica). In
**SIS2002, Atti della XLI Riunione Scientifica della Società Italiana di
Statistica**, Milano, 5-7 Giugno, 2002.

Attygalle D., Francis B., Scrucca L. (2002) Model coverage, forward
searching and multiple outlier detection. In **17th International
Workshop on Statistical Modelling**. Crete, Greece, 8-12 July, 2002.

Ranalli M.G., Scrucca L. (2002) Understanding influential observations
in regression estimation of finite population means using graphs. In
**COMPSTAT 2002, Book of abstracts**, 15th Symposium of IASC on
Computational Statistics, Berlin, Germany, 24-28 August 2002.

Scrucca L. (2001) Visualizing and assessing partial correlation
coefficients through added variable plots. In **Atti del Convegno S.Co.
2001, Modelli Complessi e Metodi Computazionali Intensivi per la Stima e
la Previsione**, Bressanone, 24-26 Settembre 2001, a cura di C. Provasi,
Cleup Editrice, Padova.

Scrucca L. (1999) Dynamic probability plot for assessing multivariate
normality. In **Atti del Convegno S.Co. 1999, Modelli Complessi e Metodi
Computazionali Intensivi per la Stima e la Previsione**, Venezia, 27-29
Settembre 1999, pp. 122--129.
:::

## Reports {#reports .unnumbered}

::: bibitem
Scrucca L., Raftery A. E. (2014) clustvarsel: A Package Implementing
Variable Selection for Model-based Clustering in R. **Technical Report,
Department of Statistics, University of Washington**, No. 629, pp.
1--27.

Fraley C., Raftery A. E., Murphy T. B., Scrucca L. (2012) mclust version
4 for R: Normal Mixture Modeling for Model-Based Clustering,
Classification, and Density Estimation. **Technical Report, Department
of Statistics, University of Washington**, No. 597, pp. 1--58

Scrucca L. (2006) Subset selection in dimension reduction methods.
**Quaderni del Dipartimento di Economia, Finanza e Statistica**,
Università degli Studi di Perugia, n. 23, Settembre 2006.

Scrucca L. (2005) Clustering multivariate spatial data based on local
measures of spatial autocorrelation. An application to the labour market
of Umbria. **Quaderni del Dipartimento di Economia, Finanza e
Statistica**, Università degli Studi di Perugia, n. 20, Ottobre 2005.
:::

## Miscellanea {#miscellanea .unnumbered}

::: bibitem
Scrucca L. (2022) Pandemia e previsioni: per l'Umbria una curva in
discesa. **AUR Focus**.
<https://www.agenziaumbriaricerche.it/focus/pandemia-e-previsioni-per-lumbria-una-curva-in-discesa/>

Scrucca L. (2021) Incidenza e impatto sul settore ospedaliero della
pandemia CoViD-19: un confronto tra regioni. **AUR Focus**.
<https://www.agenziaumbriaricerche.it/focus/incidenza-e-impatto-sul-settore-ospedaliero-della-pandemia-covid-19-un-confronto-tra-regioni/>

Serafini A., Murphy T. B., Scrucca L. (2020) Handling missing data in
model-based clustering. **arXiv:2006.02954** pre-print available at
<https://arxiv.org/abs/2006.02954>
:::
